# coding=gbk

first_name_id = {
	u"白" : "bai",
	u"蔡" : "cai",
	u"曹" : "cao",
	u"陈" : "chen",
	u"戴" : "dai",
	u"窦" : "dou",
	u"邓" : "deng",
	u"狄" : "di",
	u"杜" : "du",
	u"段" : "duan",
	u"范" : "fan",
	u"樊" : "fan",
	u"房" : "fang",
	u"风" : "feng",
	u"符" : "fu",
	u"福" : "fu",
	u"高" : "gao",
	u"古" : "gu",
	u"关" : "guan",
	u"郭" : "guo",
	u"毛" : "mao",
	u"韩" : "han",
	u"胡" : "hu",
	u"花" : "hua",
	u"洪" : "hong",
	u"侯" : "hou",
	u"黄" : "huang",
	u"贾" : "jia",
	u"蒋" : "jiang",
	u"金" : "jin",
	u"廖" : "liao",
	u"梁" : "liang",
	u"李" : "li",
	u"林" : "lin",
	u"刘" : "liu",
	u"龙" : "long",
	u"陆" : "lu",
	u"卢" : "lu",
	u"罗" : "luo",
	u"马" : "ma",
	u"牛" : "niu",
	u"庞" : "pang",
	u"裴" : "pei",
	u"彭" : "peng",
	u"戚" : "qi",
	u"齐" : "qi",
	u"钱" : "qian",
	u"乔" : "qiao",
	u"秦" : "qin",
	u"邱" : "qiu",
	u"裘" : "qiu",
	u"仇" : "qiu",
	u"沙" : "sha",
	u"商" : "shang",
	u"尚" : "shang",
	u"邵" : "shao",
	u"沈" : "shen",
	u"师" : "shi",
	u"施" : "shi",
	u"宋" : "song",
	u"孙" : "sun",
	u"童" : "tong",
	u"万" : "wan",
	u"王" : "wang",
	u"魏" : "wei",
	u"卫" : "wei",
	u"吴" : "wu",
	u"武" : "wu",
	u"萧" : "xiao",
	u"肖" : "xiao",
	u"项" : "xiang",
	u"许" : "xu",
	u"徐" : "xu",
	u"薛" : "xue",
	u"杨" : "yang",
	u"羊" : "yang",
	u"阳" : "yang",
	u"易" : "yi",
	u"尹" : "yin",
	u"俞" : "yu",
	u"赵" : "zhao",
	u"钟" : "zhong",
	u"周" : "zhou",
	u"郑" : "zheng",
	u"朱" : "zhu",

	u"东方" : "dongfang",
	u"独孤" : "dugu",
	u"慕容" : "murong",
	u"欧阳" : "ouyang",
	u"司马" : "sima",
	u"西门" : "ximen",
	u"尉迟" : "yuchi",
	u"长孙" : "zhangsun",
	u"诸葛" : "zhuge",
	u"上官" : "shangguan",
	u"夏侯" : "xiahou",
	u"闻人" : "wenren",
	u"皇甫" : "huangfu",
	u"澹台" : "tantai",
	u"公治" : "gongzhi",
	u"淳于" : "chunyu",
	u"申屠" : "shentu",
	u"公孙" : "gongsun",
	u"公羊" : "gongyang",
	u"轩辕" : "xuanyuan",
	u"令狐" : "linghu",
	u"钟离" : "zhongli",
	u"宇文" : "yuwen",
	u"慕容" : "murong",
	u"仲孙" : "zhongsun",
	u"司徒" : "situ",
	u"司空" : "sikong",
	u"端木" : "duanmu",
	u"公良" : "gongliang",
	u"百里" : "baili",
	u"东郭" : "dongguo",
	u"南郭" : "nanguo",
	u"呼延" : "huyan",
	u"羊舌" : "yangshe",
	u"东门" : "dongmen",
	u"南宫" : "nangong"
};

id_names = {
	"ai"   : u"皑艾哀",
	"an"   : u"安黯谙",
	"ao"   : u"奥傲敖骜翱",
	"ang"  : u"昂盎",
	"ba"   : u"罢霸",
	"bai"  : u"白佰",
	"ban"  : u"斑般",
	"bang" : u"邦",
	"bei"  : u"北倍贝备",
	"biao" : u"表标彪飚飙",
	"bian" : u"边卞弁忭",
	"bu"   : u"步不",
	"cao"  : u"曹草操漕",
	"cang" : u"苍仓",
	"chang": u"常长昌敞玚",
	"chi"  : u"迟持池赤尺驰炽",
	"ci"   : u"此次词茨辞慈",
	"du"   : u"独都",
	"dong" : u"东侗",
	"dou"  : u"都",
	"fa"   : u"发乏珐",
	"fan"  : u"范凡反泛帆蕃",
	"fang" : u"方访邡昉",
	"feng" : u"风凤封丰奉枫峰锋",
	"fu"   : u"夫符弗芙",
	"gao"  : u"高皋郜镐",
	"hong" : u"洪红宏鸿虹泓弘",
	"hu"   : u"虎忽湖护乎祜浒怙",
	"hua"  : u"化花华骅桦",
	"hao"  : u"号浩皓蒿浩昊灏淏",
	"ji"   : u"积极济技击疾及基集记纪季继吉计冀祭际籍绩忌寂霁稷玑芨蓟戢佶奇诘笈畿犄",
	"jian" : u"渐剑见建间柬坚俭",
	"kan"  : u"刊戡",
	"ke"   : u"可克科刻珂恪溘牁",
	"lang" : u"朗浪廊琅阆莨",
	"li"   : u"历离里理利立力丽礼黎栗荔沥栎璃",
	"lin"  : u"临霖林琳",
	"ma"   : u"马", 
	"mao"  : u"贸冒貌冒懋矛卯瑁",
	"miao" : u"淼渺邈",
	"nan"  : u"楠南",
	"pian" : u"片翩",
	"qian" : u"潜谦倩茜乾虔千",
	"qiang": u"强羌锖玱",
	"qin"  : u"亲琴钦沁芩矜",
	"qing" : u"清庆卿晴",
	"ran"  : u"冉然染燃",
	"ren"  : u"仁刃壬仞",
	"sha"  : u"沙煞",
	"shang": u"上裳商",
	"shen" : u"深审神申慎参莘",
	"shi"  : u"师史石时十世士诗始示适炻",
	"shui" : u"水",
	"si"   : u"思斯丝司祀嗣巳",
	"song" : u"松颂诵",
	"tang" : u"堂唐棠瑭",
	"tong" : u"统通同童彤仝",
	"tian" : u"天田忝",
	"wan"  : u"万宛晚",
	"wei"  : u"卫微伟维威韦纬炜惟玮为",
	"wu"   : u"吴物务武午五巫邬兀毋戊",
	"xi"   : u"西席锡洗夕兮熹惜",
	"xiao" : u"潇萧笑晓肖霄骁校",
	"xiong": u"熊雄",
	"yang" : u"羊洋阳漾央秧炀飏鸯",
	"yi"   : u"易意依亦伊夷倚毅义宜仪艺译翼逸忆怡熠沂颐奕弈懿翊轶屹猗翌",
	"yin"  : u"隐因引银音寅吟胤訚烟荫",
	"ying" : u"映英影颖瑛应莹郢鹰",
	"you"  : u"繇幽悠右忧猷酉",
	"yu"   : u"渔郁寓于余玉雨语预羽舆育宇禹域誉瑜屿御渝毓虞禺豫裕钰煜聿",
	"zhi"  : u"制至值知质致智志直治执止置芝旨峙芷挚郅炙雉帜",
	"zhong": u"中忠钟衷",
	"zhou" : u"周州舟胄昼",
	"zhu"  : u"竹主驻朱祝诸珠著竺",
	"zhuo" : u"卓灼灼拙琢濯斫擢焯酌",
	"zi"   : u"子资兹紫姿孜梓秭",
	"zong" : u"宗枞",
	"zu"   : u"足族祖卒",
	"zuo"  : u"作左佐笮凿"
};

name_id = {}
for id,names in id_names.iteritems():
	for name in names:
		name_id[name] = id


def get_id(name):
	name_start = 2; # 默认复姓，钟离 优先解析为复姓
	first_name = name[:name_start]
	first_id = first_name_id.get(first_name)
	if first_id == None:
		name_start = 1
		first_name = name[:name_start]
		first_id = first_name_id.get(first_name)
	sencod_name = name[name_start:]
	sencod_id = ""
	for name in sencod_name:
		sencod_id += name_id.get(name,"")

	return first_id + " " + sencod_id

